export component Wallpaper15 inherits Rectangle {
    in property <bool> is-preview: false;
    background: #14532d;
    Rectangle { width: is-preview ? 40px : 300px; height: is-preview ? 40px : 300px; x: parent.width/2 - (is-preview ? 15px : 100px); y: parent.height/2 - (is-preview ? 20px : 150px); border-radius: is-preview ? 20px : 150px; background: #16653499; }
    Rectangle { width: is-preview ? 40px : 300px; height: is-preview ? 40px : 300px; x: parent.width/2 - (is-preview ? 30px : 200px); y: parent.height/2 - (is-preview ? 20px : 150px); border-radius: is-preview ? 20px : 150px; background: #15803d99; }
}