export component Wallpaper07 inherits Rectangle {
    in property <bool> is-preview: false;
    background: @linear-gradient(180deg, #7f1d1d 0%, #450a0a 100%);
    Rectangle { width: parent.width; height: is-preview ? 30px : 200px; y: parent.height/2; background: #00000040; }
    Rectangle { width: is-preview ? 30px : 150px; height: is-preview ? 30px : 150px; x: parent.width/2 - (is-preview ? 15px : 75px); y: parent.height/2 - (is-preview ? 15px : 75px); background: #ef4444; border-radius: is-preview ? 4px : 16px; }
}