export global StoreSpacing {
    in-out property <length> space-xs: 4px;
    in-out property <length> space-sm: 8px;
    in-out property <length> space-md: 12px;
    in-out property <length> space-lg: 16px;
    in-out property <length> space-xl: 20px;
    in-out property <length> space-xxl: 24px;
    
    in-out property <length> padding-sm: 8px;
    in-out property <length> padding-md: 12px;
    in-out property <length> padding-lg: 16px;
    in-out property <length> padding-xl: 20px;
    in-out property <length> padding-xxl: 24px;
}
