export global StoreTypography {
    in-out property <string> font-family: "sans-serif";
    in-out property <length> font-size-xs: 12px;
    in-out property <length> font-size-sm: 14px;
    in-out property <length> font-size-base: 16px;
    in-out property <length> font-size-lg: 20px;
    in-out property <length> font-size-xl: 24px;
    in-out property <int> font-weight-normal: 400;
    in-out property <int> font-weight-bold: 700;
    in-out property <int> font-weight-extra-bold: 900;
}
