import { SumerConsoleWindow } from "terminal-window.slint";

export component AppWindow inherits Window {
    title: "شيل دجلة - موجه الأوامر";
    width: 700px;
    height: 480px;
    background: #090d16;
    
    // كولباك تنفيذ الأوامر مع الباك-أند
    callback execute-command(string) -> string;

    SumerConsoleWindow {
        width: 100%;
        height: 100%;
        execute-command(cmd) => {
            return root.execute-command(cmd);
        }
    }
}
