export global SumerTheme {
    // Colors
    out property <color> primary-accent: #38bdf8;
    out property <color> secondary-accent: #0284c7;
    out property <color> success: #10b981;
    out property <color> warning: #f97316;
    out property <color> danger: #ef4444;
    out property <color> dark-bg: #0f172a;
    out property <color> light-bg: #f8fafc;
    out property <color> border-dark: #ffffff1b;
    out property <color> border-light: #00000015;
    
    // Animations
    out property <duration> fast-anim: 150ms;
    out property <duration> normal-anim: 200ms;
    out property <duration> slow-anim: 350ms;
    
    // Shadows
    out property <length> shadow-blur: 24px;
}
