export global TvSpacing {
    in-out property <length> space-xs: 4px;
    in-out property <length> space-sm: 8px;
    in-out property <length> space-md: 12px;
    in-out property <length> space-lg: 16px;
    in-out property <length> space-xl: 20px;
    in-out property <length> space-xxl: 24px;
    in-out property <length> space-huge: 25px;
    
    in-out property <length> padding-xs: 4px;
    in-out property <length> padding-sm: 8px;
    in-out property <length> padding-md: 12px;
    in-out property <length> padding-lg: 16px;
    in-out property <length> padding-xl: 20px;
    in-out property <length> padding-xxl: 24px;
    in-out property <length> padding-giant: 45px;
    
    in-out property <length> radius-sm: 8px;
    in-out property <length> radius-md: 12px;
    in-out property <length> radius-lg: 16px;
    in-out property <length> radius-full: 9999px;
}
